import { render } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { Streamdown } from "../index";

describe("GenerateText Integration with Streamdown", () => {
  it("should render markdown generated by generateText correctly", () => {
    // Mock the generateText response with realistic AI-generated markdown
    const mockMarkdown = `# Generated Holiday

## World Kindness Day

**Date:** March 15th
**Traditions:**
- Perform random acts of kindness
- Share positive messages on social media
- Organize community service events

This holiday celebrates compassion and empathy in our daily lives.`;

    // Test that Streamdown can render the generated markdown
    const { container } = render(<Streamdown>{mockMarkdown}</Streamdown>);

    // Verify that Streamdown renders the content
    const wrapper = container.firstElementChild;
    expect(wrapper).toBeTruthy();

    // Check that the content is processed correctly
    const allText = wrapper?.textContent || "";
    expect(allText).toContain("Generated Holiday");
    expect(allText).toContain("World Kindness Day");
    expect(allText).toContain("March 15th");
    expect(allText).toContain("random acts of kindness");
  });

  it("should handle various markdown elements from AI generation", () => {
    const aiGeneratedContent = `# AI-Generated Article

## Introduction

This article was generated by an AI model using \`generateText()\`.

### Key Features

- **Bold text** for emphasis
- *Italic text* for subtlety
- \`inline code\` for technical terms

> This is a blockquote from the AI.

1. First item
2. Second item

---

End of article.`;

    const { container } = render(<Streamdown>{aiGeneratedContent}</Streamdown>);

    const wrapper = container.firstElementChild;
    expect(wrapper).toBeTruthy();

    const allText = wrapper?.textContent || "";
    expect(allText).toContain("AI-Generated Article");
    expect(allText).toContain("Introduction");
    expect(allText).toContain("generateText()");
    expect(allText).toContain("Bold text");
    expect(allText).toContain("Italic text");
    expect(allText).toContain("blockquote");
    expect(allText).toContain("End of article");
  });

  it("should handle incomplete markdown from streaming AI responses", () => {
    // Simulate incomplete markdown that might come from streaming AI
    const incompleteMarkdown = `# Streaming Response

This is a **bold text that is cut off
And here's an incomplete [link
Also an unfinished code block:

\`\`\`javascript
function hello() {
  console.log("Hello");
\`\`\``;

    const { container } = render(<Streamdown>{incompleteMarkdown}</Streamdown>);

    const wrapper = container.firstElementChild;
    expect(wrapper).toBeTruthy();

    const allText = wrapper?.textContent || "";
    expect(allText).toContain("Streaming Response");
    expect(allText).toContain("bold text that is cut off");
    expect(allText).toContain("incomplete link");
    expect(allText).toContain("javascript");
  });

  it("should render complex AI-generated content with math and diagrams", () => {
    const complexContent = `# Advanced AI Content

## Mathematics

The Pythagorean theorem: $a^2 + b^2 = c^2$

\`\`\`mermaid
graph TD
    A[Start] --> B{Is it working?}
\`\`\`

## Code Example

\`\`\`python
def fibonacci(n):
    return n
\`\`\`

This demonstrates the full capabilities of AI-generated content rendering.`;

    const { container } = render(<Streamdown>{complexContent}</Streamdown>);

    const wrapper = container.firstElementChild;
    expect(wrapper).toBeTruthy();

    const allText = wrapper?.textContent || "";
    expect(allText).toContain("Advanced AI Content");
    expect(allText).toContain("Pythagorean theorem");
    expect(allText).toContain("a^2 + b^2 = c^2");
    expect(allText).toContain("Loading diagram");
    expect(allText).toContain("python");
    expect(allText).toContain("This demonstrates");
  });
});